<!DOCTYPE html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
</head>
<body>
<p>edit script : <?php
echo $name;
if ($noimg != "")
  echo ", <a href=\"/plantuml_out/work/$name.png\">image</a>, <a href=\"".plantuml_link('watch', $name)."\">watch</a></p>";
else
  echo "</p><p><img src=\"/plantuml_out/work/$name.png\"></p>";
?></p>
<textarea rows=<?php echo "$rows"; ?> cols=80 name="script" form="updateform">
<?php echo htmlentities ($script_text); ?>
</textarea><br />
<form method="post" action="<?php echo plantuml_link('update', $name, ['noimg'=>$noimg]); ?>" id="updateform">
<input type="submit">
</form>

<p>git commit message. if empty, will not make changeset.<br />
<textarea rows=5 cols=80 name="message" form="updateform"/>
</textarea><br/>
<?php echo $file_status; ?>
</p>

<p><a href="/plantuml?&<?php echo "noimg=$noimg"; ?>">script list</a>...<br />
<a href="<?php echo plantuml_link('edit', $name, ['noimg'=>$noimg]); ?>">reset and refresh</a> this page<br />
<a href="<?php echo plantuml_link('fetch_repo', $name, ['noimg'=>$noimg]); ?>">fetch updated from repository</a><br />
<a href="<?php echo plantuml_link('fetch_repo', $name, ['noimg'=>'true']); ?>">donot display image</a><br />
<a href="<?php echo plantuml_link('fetch_repo', $name, ['noimg'=>'false']); ?>">display image</a><br />
<p><?php echo $tail_message; ?></p>
</body>
<?php // vim:set sw=2 et: ?>
