<!DOCTYPE html>
<head>
  <title><?php echo $name; ?></title>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <style type="text/css">
img {
  vertical-align: middle;
  //margin: auto;
}
  </style>
</head>
<body>
<div id="watch_title"><?php echo $mtime; ?></div>
<img id="watch_img" src="<?php echo plantuml_img_link($name)."?mtime=$mtime"; ?>" onload="check_changes();">
<script>

var current_mtime = <?php echo $mtime; ?>;

function check_changes()
{
  url = '/plantuml/wait_changes/<?php echo $name; ?>?mtime='+current_mtime;
  console.log('fetch url : '+url);

  fetch(url).then(function(response) {
    response.json().then(function(json) {
      if (json.mtime != 0 && json.mtime != current_mtime)
      {
        console.log('mtime changes from '+current_mtime+' to '+json.mtime+'. message : '+json.message);

        current_mtime = json.mtime;
        document.getElementById('watch_img').src='<?php echo plantuml_img_link($name); ?>?mtime='+current_mtime;
        document.getElementById('watch_title').innerHTML=current_mtime;
      }
      else
      {
        console.log('mtime : '+json.mtime+'. message : '+json.message);
        check_changes();
      }
    });
  });
}

(function()
{
})();
</script>
<?php
?>
</body>
<?php // vim:set sw=2 et: ?>
