<!DOCTYPE html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <title><?php echo $name; ?></title>
 
  <script src="/codebase/dhtmlxgantt.js"></script>
  <link href="/codebase/dhtmlxgantt.css" rel="stylesheet">
 
  <style type="text/css">
html, body{
  height:100%;
  padding:0px;
  margin:0px;
  overflow: hidden;
}

.gantt_task_cell.week_end{
  background-color: #EFF5FD;
}
.gantt_task_row.gantt_selected .gantt_task_cell.week_end{
  background-color: #F8EC9C;
}

  </style>
</head>
<body>
  <div id="gantt_here" style='width:100%; height:100%;'></div>
  <script type="text/javascript">
    gantt.config.xml_date = "%Y-%m-%d %H:%i:%s";
    gantt.config.work_time = true;
    gantt.config.order_branch = true;
    gantt.config.order_branch_free = true;
     
    gantt.init("gantt_here");
    gantt.load("/gantt/<?php echo $name; ?>/data");

    gantt.templates.task_cell_class = function(task, date){
      if(!gantt.isWorkTime(date))
        return "week_end";
      return "";
    };

    var workday = [<?php
foreach ($workday as $day)
{
  if ($day)
    echo 'true,';
  else
    echo 'false,';
}
?> ];
    for (var i=0; i<workday.length; i++)
    {
      gantt.setWorkTime ({day:i, hours: workday[i]});
    }

    var dp = new gantt.dataProcessor("/gantt/<?php echo $name; ?>/data");
    dp.init(gantt);
    dp.setTransactionMode("REST");
  </script>
</body>
